################################################################################
# File Name                      : robot_geneticalgorithm.py
# UE                             : LU3IN025 - IA & Jeux - TME02
# Writers                        : BENNOUNA Kamil - 21204602
#                                : KHENNOUSSI Hanane - 21318242
# Creation date                  : 05/02/2026
# Last update date               : 05/02/2026 @ 1340
# Description                    : Genetic algorithm (1+1) for behavioral strategy search
################################################################################

from robot import *
import math

nb_robots = 0
debug = False

class Robot_player(Robot):

    team_name = "GeneticAlgorithm"
    robot_id = -1
    iteration = 0

    param = []  # Current parent
    child_param = []  # Child generated by mutation
    best_param = []
    it_per_evaluation = 400
    evaluations = 0
    trial = 0

    score = 0.0
    child_score = 0.0
    best_score = -float("inf")
    best_trial = -1

    log_translation_at_start = 0.0
    log_rotation_at_start = 0.0

    replay_mode = False
    replay_iteration = 0
    replay_length = 1000

    x_0 = 0
    y_0 = 0
    theta_0 = 0 # in [0,360]

    def __init__(self, x_0, y_0, theta_0, name="n/a", team="n/a", evaluations=0, it_per_evaluation=0):
        global nb_robots
        self.robot_id = nb_robots
        nb_robots += 1
        self.x_0 = x_0
        self.y_0 = y_0
        self.theta_0 = theta_0
        self.param = [random.randint(-1, 1) for i in range(8)]
        self.child_param = list(self.param)
        self.best_param = list(self.param)
        self.it_per_evaluation = it_per_evaluation if it_per_evaluation > 0 else 400
        self.evaluations = evaluations if evaluations > 0 else 500
        super().__init__(x_0, y_0, theta_0, name=name, team=team)

    def reset(self):
        super().reset()

    def _reset_log_tracking(self):
        """Reinitialize log tracking for the current trial."""
        self.log_translation_at_start = self.log_sum_of_translation
        self.log_rotation_at_start = self.log_sum_of_rotation

    def _mutate(self, parent):
        """Create child by mutating parent (1 parameter changed, new value differs)."""
        child = list(parent)
        # Select random parameter
        index = random.randint(0, 7)
        current_value = child[index]
        
        # Generate new value different from current
        # Possible values are {-1, 0, 1}
        possible_values = [-1, 0, 1]
        possible_values.remove(current_value)
        child[index] = random.choice(possible_values)
        
        return child

    def step(self, sensors, sensor_view=None, sensor_robot=None, sensor_team=None):

        # Update score during evaluation (not in replay mode)
        if not self.replay_mode and self.iteration > 0 and self.iteration % self.it_per_evaluation != 0:
            delta_translation = self.log_sum_of_translation - self.log_translation_at_start
            delta_rotation = self.log_sum_of_rotation - self.log_rotation_at_start

            if delta_translation >= 0 and delta_rotation >= 0:
                rotation_effective = min(1.0, abs(delta_rotation))
                self.child_score += delta_translation * (1 - rotation_effective)
                self._reset_log_tracking()

        # At each evaluation end (every it_per_evaluation iterations)
        if self.iteration % self.it_per_evaluation == 0:
            # Display results if not first iteration and not in replay mode
            if self.iteration > 0 and not self.replay_mode:
                print("\tparent parameters    =", self.param)
                print("\tchild parameters     =", self.child_param)
                print("\tchild score          =", self.child_score)
                print("\ttranslations         =", self.log_sum_of_translation, "; rotations =", self.log_sum_of_rotation)
                print("\tdistance from origin =", math.sqrt((self.x - self.x_0) ** 2 + (self.y - self.y_0) ** 2))
                
                # Selection (1+1): keep best between parent and child
                if self.child_score > self.score:
                    print("Child is better! Replacing parent.")
                    self.param = list(self.child_param)
                    self.score = self.child_score
                else:
                    print("Parent is better. Child discarded.")
                
                # Update global best
                if self.score > self.best_score:
                    self.best_score = self.score
                    self.best_param = list(self.param)
                    self.best_trial = self.trial
                    print("New best strategy:", self.best_trial, "score =", self.best_score)
                    print("Best parameters    =", self.best_param)

            # Start new generation or enter replay mode
            if not self.replay_mode:
                self.trial += 1
                if self.trial <= self.evaluations:
                    # Create child by mutating current parent
                    self.child_param = self._mutate(self.param)
                    self.child_score = 0.0
                    self._reset_log_tracking()
                    print("Generation no.", self.trial, "- Evaluating mutated child")
                else:
                    # Enter replay mode
                    self.replay_mode = True
                    self.param = list(self.best_param)
                    self.replay_iteration = 0
                    self._reset_log_tracking()
                    print("Budget exhausted.")
                    print("Best strategy was no.", self.best_trial, "with score", self.best_score)
                    print("Replaying best parameters:", self.best_param)

            # Replay loop: reset every replay_length iterations
            if self.replay_mode:
                self.replay_iteration = (self.replay_iteration + 1) % self.replay_length
                if self.replay_iteration == 0:
                    self._reset_log_tracking()

            self.iteration += 1
            return 0, 0, True  # ask for reset

        # Control computation (Perceptron with tanh activation)
        # Use current child during evaluation, or best behavior in replay mode
        params = self.param if self.replay_mode else self.child_param
        
        translation = math.tanh(
            params[0]
            + params[1] * sensors[sensor_front_left]
            + params[2] * sensors[sensor_front]
            + params[3] * sensors[sensor_front_right]
        )
        rotation = math.tanh(
            params[4]
            + params[5] * sensors[sensor_front_left]
            + params[6] * sensors[sensor_front]
            + params[7] * sensors[sensor_front_right]
        )

        if debug == True:
            if self.iteration % 100 == 0:
                print("Robot", self.robot_id, "(team " + str(self.team_name) + ")", "at step", self.iteration, ":")
                print("\tsensors (distance, max is 1.0)  =", sensors)
                print("\ttype (0:empty, 1:wall, 2:robot) =", sensor_view)
                print("\trobot's name (if relevant)      =", sensor_robot)
                print("\trobot's team (if relevant)      =", sensor_team)

        self.iteration += 1
        return translation, rotation, False
